### PR TITLE
Add 37 New Icons

### PR DESCRIPTION
**Pull request by thenanobel**
Hi,

I've added 37 new icons for 38 apps. Although, there is an icon for `F-Droid` already, I've added another one. If you find it better you may use it instead of the current one. I hope, most of these icons are good enough for inclusion. But, if you find any icon imperfect, please, let me know. If any of these icons needs to be improved. I'll do that.

Here you can find a list of all the icons I've added, [github.com/thenanobel/added-icons-for-paper-android](https://github.com/thenanobel/added-icons-for-paper-android).

Thanks.

### CODE REVIEW

**Comment by beli3ver** [comment]
Man, amazing work thanks.
I will integrate tomorrow the new icons.

**Comment by thenanobel** [comment]
Thanks for your appreciation toward my contribution. :smiley:

**Comment by beli3ver** [comment]
You are welcome.
Can you create a icon for c:geo?

Am 19. August 2017 19:52:25 MESZ schrieb Nave Nobel <notifications@github.com>:
>Thanks for your appreciation toward my contribution. :smiley: 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/Paper-FOSS-Theme/pull/28#issuecomment-323537898

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by thenanobel** [comment]
I think, I can. But, I'm afraid, it'll take some time. As, I'm busy a bit.

**Comment by beli3ver** [comment]
No Problem take your time

Am 20. August 2017 06:55:02 MESZ schrieb Nave Nobel <notifications@github.com>:
>I think, I can. But, I'm afraid, it'll take some time. As, I'm busy a
>bit.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/Paper-FOSS-Theme/pull/28#issuecomment-323563601

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
